# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - rm -rf docs/recipes
      - mkdir -p docs/recipes
      - for: sources
        cmd: chef recipe '{{.ITEM}}' --format markdown > '{{joinPath "docs" .ITEM}}.md'
    sources:
      - recipes/**/*.cook
    generates:
      - docs/recipes/**/*.cook.md
